channels:
- conda-forge
- bioconda
dependencies:
- bioconda::bioconductor-biostrings=2.70.1
- bioconda::bioconductor-deseq2=1.42.0
- bioconda::bioconductor-enrichplot=1.22.0
- bioconda::bioconductor-fgsea=1.28.0
- bioconda::bioconductor-genomicfeatures=1.54.1
- bioconda::bioconductor-gosemsim=2.28.0
- bioconda::bioconductor-gviz=1.46.1
- bioconda::bioconductor-msa=1.34.0
- bioconda::bioconductor-qvalue=2.34.0
- bioconda::bioconductor-rtracklayer=1.62.0
- bioconda::bioconductor-tximeta=1.20.1
- bioconda::bioconductor-tximport=1.30.0
- bioconda::bioconductor-variantannotation=1.48.1
- bioconda::salmon=1.10.3
- conda-forge::ipykernel=6.29.3
- conda-forge::jupyterlab=4.2.0
- conda-forge::r-base=4.3.3
- conda-forge::r-biocmanager=1.30.23
- conda-forge::r-downloader=0.4
- conda-forge::r-ggnewscale=0.4.10
- conda-forge::r-kableextra=1.4.0
- conda-forge::r-plotly=4.10.4
- conda-forge::r-remotes=2.5.0
- conda-forge::r-reshape2=1.4.4
- conda-forge::r-seqinr=4.2-36
- conda-forge::r-tidyverse=2.0.0
- conda-forge::wget=1.21.4